package com.imatia.statemachine.events;

public enum Eventos {
	RECOGIDO_REPARTO,
	RECOGIDO_INCIDENCIA,
	REPARTO_INCIDENCIA,
	INCIDENCIA_REPARTO,
	RECOGIDO_ENTREGADO,
	REPARTO_ENTREGADO,
	INCIDENCIA_ENTREGADO
}
